### ISSUE TITLE
Using the latest version of some npm packages breaks kinesalite.

### ISSUE THREAD

**Issue by pharaun** [mhart/kinesalite#27] opened 2016-02-10 21:25 UTC
```
kinesalite@1.11.3 node_modules/kinesalite
├── lock@0.1.2
├── once@1.3.3 (wrappy@1.0.1)
├── node-uuid@1.4.7
├── minimist@1.2.0
├── lazy@1.0.11
├── async@1.5.2
├── bignumber.js@2.1.4
├── memdown@1.1.2 (inherits@2.0.1, ltgt@1.0.2, functional-red-black-tree@1.0.1, abstract-leveldown@2.4.1)
├── levelup@1.3.1 (xtend@4.0.1, prr@1.0.1, level-codec@6.1.0, semver@5.1.0, level-errors@1.0.4, deferred-leveldown@1.2.1, level-iterator-stream@1.3.1)
├── level-sublevel@6.5.4 (typewiselite@1.0.0, ltgt@2.1.2, xtend@4.0.1, pull-stream@2.21.0, levelup@0.19.1, bytewise@1.1.0)
└── leveldown@1.4.4 (bindings@1.2.1, fast-future@1.0.1, abstract-leveldown@2.4.1, nan@2.2.0, prebuild@2.9.0)

root@4328213c05f9:/code# /usr/local/bin/kinesalite 

module.js:340
    throw err;
          ^
Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kinesalite/db/index.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I was able to patch this by removing all of the `^` in the dependencies,  which to my understanding is `this version or higher` and kinesalite started to work.

May want to look into finding which version of ie memdown and so on are breaking and put in an upper bound or so.

**Comment by mhart** [comment] 2016-02-10 21:45
I'm unable to reproduce this:

```
$  npm install kinesalite
/
> leveldown@1.4.4 install /proj/node_modules/kinesalite/node_modules/leveldown
> prebuild --install

kinesalite@1.11.3 node_modules/kinesalite
├── lock@0.1.2
├── async@1.5.2
├── bignumber.js@2.1.4
├── node-uuid@1.4.7
├── minimist@1.2.0
├── once@1.3.3 (wrappy@1.0.1)
├── lazy@1.0.11
├── memdown@1.1.2 (inherits@2.0.1, ltgt@1.0.2, functional-red-black-tree@1.0.1, abstract-leveldown@2.4.1)
├── level-sublevel@6.5.4 (ltgt@2.1.2, typewiselite@1.0.0, xtend@4.0.1, pull-stream@2.21.0, bytewise@1.1.0, levelup@0.19.1)
├── levelup@1.3.1 (prr@1.0.1, xtend@4.0.1, level-codec@6.1.0, semver@5.1.0, level-errors@1.0.4, deferred-leveldown@1.2.1, level-iterator-stream@1.3.1)
└── leveldown@1.4.4 (bindings@1.2.1, fast-future@1.0.1, abstract-leveldown@2.4.1, nan@2.2.0, prebuild@2.9.1)

$  ./node_modules/.bin/kinesalite
Listening at http://:::4567
```

Can you give me exact steps to reproduce?

**Comment by mhart** [comment] 2016-02-10 21:47
(Also, what version of Node and npm are you using? I was using Node v4.3.0, npm v2.14.18)

**Comment by mhart** [comment] 2016-02-16 06:07
@pharaun I'm closing this as I'm unable to reproduce it – happy to reopen if you can give me more detail, thanks!

**Comment by pharaun** [comment] 2016-02-16 23:49
Yeah sorry about that, long holiday and been occupied with other things at work.  Anyway here's additional information.

This is in an Ubuntu Trusty docker image:
```
$ apt-get install git nodejs nodejs-legacy npm
$ npm install -g kinesalite
$ kinesalite --port 4567
```

Then it crashes with:

```
root@2e37a08847df:/# kinesalite --port 4567

module.js:340
    throw err;
          ^
Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kinesalite/db/index.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Now I was able to workaround this by making all version requirement strict (without ^) and that started to work.

In the end what we ended up settling upon was:

```
$ apt-get install python-pip git
$ pip install nodeenv
$ nodeenv --node=4.2.6 --prebuilt env
$ git clone --branch v1.11.3 https://github.mhart/kinesalite.git
$ cd kinesalite
$ ../env/bin/activate && ../env/bin/npm install
$ ./cli.js --port 4567
```

And that works.  So if you don't want to support this ticket, that's ok, I just wanted to comment that it doesn't work "out of the box" with the default recommended `npm install -g kinesalite`

**Comment by mhart** [comment] 2016-02-17 00:26
Cool, thanks! It definitely should work out of the box – and indeed it does on my Mac (with all the latest versions, not pinned versions).

Must be something env-specific – I'll try with an Ubuntu docker image now

**Comment by mhart** [comment] 2016-02-17 01:32
Ok – this is just due to a bug in the reeeeeeally old version of npm used in your example (1.3.10) – any npm version > 1.4 should install this just fine.

All users should really be updating their npm version (at least using `npm install -g npm@1` if they're on v0.10, but preferably `npm install -g npm@2` or `npm install -g npm@3` – because I don't think npm v1.x is supported anymore)

Closing this again as it's an issue with npm, not this library.

**Closed by mhart** 2016-02-17 01:32 UTC

**Comment by pharaun** [comment] 2016-02-17 20:22
Works for me, maybe worth adding a small comment/link on your readme since I'm new to the nodejs ecosystem so wasn't aware of this.

**Comment by cbmanica** [comment] 2016-02-19 21:41
Hi, I'm afraid I've spent 45 minutes attempting to make this work, and even with npm 3.7.3 and reinstalling kinesalite about 10 times, I still cannot get a working kinesalite install. The gist from

> sudo npm -v > k.out; sudo npm uninstall -g kinesalite >> k.out 2>&1; sudo npm rebuild >> k.out 2>&1; sudo npm install -g kinesalite >> k.out 2>&1; kinesalite >> k.out 2>&1

is

https://gist.github.com/cbmanica/18364589c359be28545a

**Comment by mhart** [comment] 2016-02-20 00:29
@cbmanica does it work with npm v2.x?

(I also notice there are some permissions errors in your npm install command, but not sure if they're related to this issue)

**Comment by mhart** [comment] 2016-02-20 01:07
@cbmania also, did you install it previously with another version of npm?

Try clearing your npm cache and see if that helps

**Comment by cbmanica** [comment] 2016-02-23 18:33
@mhart Ah, clearing the cache did it - I had installed with 1.x before realizing that this was an issue. Thanks!
